### ISSUE TITLE
[Bug]: Crashed on video with lots of views and comments with "HttpError 400 when requesting"

### ISSUE THREAD

**Issue by SoNickRND** [ThioJoe/YT-Spammer-Purge#1003]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to scan [the video ](https://www.youtube.com/watch?v=sP5agpp4tJ4) but after a few minutes of scanning the app crashed, so the log is below. If it's not a real issue, feel free to close this ticket.

### Release version

2.16.10

### Steps to reproduce

1. Didn't try to reproduce, to be honest.
2. 
3. 

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Scanning 1/1: Разговор с тем, кто поддерживает армию России / вДудь

Traceback (most recent call last):ments Scanned: 51350 | Replies Scanned: 18493 | Matches Found So Far: 20
  File "Scripts\operations.py", line 34, in get_comments
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 937, in execute
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet%2C+replies&videoId=sP5agpp4tJ4&maxResults=100&pageToken=QURTSl9pMkdGMm9GU1AzbVVqMXJseHlCcXV1dEJZYjlUTVBab0g4MGhva2prWGpJOHZ6Tm5aejJHNHQ0TlRHbE1NLW9ldGdCdzVUNU9NM0w%3D&fields=nextPageToken%2Citems%2Fsnippet%2FtopLevelComment%2Fid%2Citems%2Freplies%2Fcomments%2Citems%2Fsnippet%2FtotalReplyCount%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FvideoId%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FauthorChannelId%2Fvalue%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FauthorDisplayName%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FtextDisplay%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FpublishedAt&textFormat=plainText&alt=json returned "The API server failed to successfully process the request. While this can be a transient error, it usually indicates that the request's input is invalid. Check the structure of the <code>commentThread</code> resource in the request body to ensure that it is valid.". Details: "[{'message': "The API server failed to successfully process the request. While this can be a transient error, it usually indicates that the request's input is invalid. Check the structure of the <code>commentThread</code> resource in the request body to ensure that it is valid.", 'domain': 'youtube.commentThread', 'reason': 'processingFailure', 'location': 'body', 'locationType': 'other'}]">
------------------------------------------------
 ERROR!   Error Message: <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet%2C+replies&videoId=sP5agpp4tJ4&maxResults=100&pageToken=QURTSl9pMkdGMm9GU1AzbVVqMXJseHlCcXV1dEJZYjlUTVBab0g4MGhva2prWGpJOHZ6Tm5aejJHNHQ0TlRHbE1NLW9ldGdCdzVUNU9NM0w%3D&fields=nextPageToken%2Citems%2Fsnippet%2FtopLevelComment%2Fid%2Citems%2Freplies%2Fcomments%2Citems%2Fsnippet%2FtotalReplyCount%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FvideoId%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FauthorChannelId%2Fvalue%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FauthorDisplayName%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FtextDisplay%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FpublishedAt&textFormat=plainText&alt=json returned "The API server failed to successfully process the request. While this can be a transient error, it usually indicates that the request's input is invalid. Check the structure of the <code>commentThread</code> resource in the request body to ensure that it is valid.". Details: "[{'message': "The API server failed to successfully process the request. While this can be a transient error, it usually indicates that the request's input is invalid. Check the structure of the <code>commentThread</code> resource in the request body to ensure that it is valid.", 'domain': 'youtube.commentThread', 'reason': 'processingFailure', 'location': 'body', 'locationType': 'other'}]">
Status Code: 400
    Reason: processingFailure

 [!!] Processing Error - Sometimes this error fixes itself. Try just running the program again. !!
This issue is often on YouTube's side, so if it keeps happening try again later.
(This also occurs if you try deleting comments on someone elses video, which is not possible.)
------------------------------------------------

[!] Fatal Error Occurred During Scan!  Read the important info below!

Program must skip the rest of the scan. Comments already scanned can still be used to create a log file (if you choose)
  > You won't be able to delete/hide any comments like usual, but you can exclude users before saving the log file
  > Then, you can delete the comments later using the mode that removes comments using a pre-existing list

 Press Enter to continue...
```

**Comment by ThioJoe** [comment]
Yea this is just something that randomly happens, it was a problem on YouTube's side
