### ISSUE TITLE
[Bug]: Module "googleapiclient" not found

### ISSUE THREAD

**Issue by z9ctn4fn** [ThioJoe/YT-Spammer-Purge#1042]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to boot up the thing on Ubuntu but then it said module "regex" was not found.

### Release version

2.17.0

### Steps to reproduce

1. Follow the directions for installing for Linux on an Ubuntu 20.04 system
2. Try and boot it up with python3 or python3.9
3. Error

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
Importing Script Modules...
Traceback (most recent call last):
  File "/home/____/YT-Spammer-Purge-2.17.0/YTSpammerPurge.py", line 44, in <module>
    from Scripts.shared_imports import *
  File "/home/____/YT-Spammer-Purge-2.17.0/Scripts/shared_imports.py", line 4, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'
```

**Comment by z9ctn4fn** [comment]
Okay, now that issue is fixed, now I'm getting this error:

Importing Script Modules...
Traceback (most recent call last):
  File "/home/____/YT-Spammer-Purge-2.17.0/YTSpammerPurge.py", line 45, in <module>
    import Scripts.auth as auth
  File "/home/____/YT-Spammer-Purge-2.17.0/Scripts/auth.py", line 4, in <module>
    import Scripts.validation as validation
  File "/home/____/YT-Spammer-Purge-2.17.0/Scripts/validation.py", line 5, in <module>
    import Scripts.utils as utils
  File "/home/____/YT-Spammer-Purge-2.17.0/Scripts/utils.py", line 6, in <module>
    from googleapiclient.errors import HttpError
ModuleNotFoundError: No module named 'googleapiclient'

**Comment by z9ctn4fn** [comment]
Fixed it myself, just a bunch of missing stuff
