### ISSUE TITLE
[Bug]: (Enter short, one sentence summary of bug here)

### ISSUE THREAD

**Issue by trek-e** [ThioJoe/YT-Spammer-Purge#1049]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to install YTSpmmerPurge 2.17 after removing an older version

### Release version

2.17

### Steps to reproduce

1. Downlaod the Zip File / Extract
2. run pip3 install -r requirements.txt with no errors / requirements met
3. validate client_secrets.json is in same directory
4. run python3 YTSpammerPurge.py

### What platform are you seeing this problem on?

MacOS

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/trekkie/Downloads/YT-Spammer-Purge-2.17.0/YTSpammerPurge.py", line 49, in <module>
    import Scripts.logging as logging
  File "/Users/trekkie/Downloads/YT-Spammer-Purge-2.17.0/Scripts/logging.py", line 14, in <module>
    from Levenshtein import ratio

and program will not execute.   The older (2.15 maybe?) version I had on there had been working for some time, i just wanted to update so I created a new directory, put 2.17 in it, and attempted to run it.

i've tried brew upgrade/update to make sure ntohing was out of date there, and my google searching on the errors has not helped.
```

**Comment by Firecul** [comment]
There is possibly something in #523 that might help.
