### ISSUE TITLE
Some authorisation bug

### ISSUE THREAD

**Issue by SoNickRND** [ThioJoe/YT-Spammer-Purge#1098]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to authorize but then I got this "report this please" message.

### Steps to reproduce

1. 
2. 
3. 

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Getting info about latest updates...

>  A new spam list update is available. Downloading...
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 72, in create_connection
  File "socket.py", line 954, in getaddrinfo
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1040, in _validate_conn
  File "urllib3\connection.py", line 358, in connect
  File "urllib3\connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002E486541A60>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /ThioJoe/YT-Spam-Lists/releases/download/2024.02.16/2024.02.16.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002E486541A60>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Scripts\files.py", line 389, in getRemoteFile
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /ThioJoe/YT-Spam-Lists/releases/download/2024.02.16/2024.02.16.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002E486541A60>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1674, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 232, in main
  File "Scripts\files.py", line 92, in check_lists_update
  File "Scripts\files.py", line 399, in getRemoteFile
TypeError: unsupported operand type(s) for +: 'ConnectionError' and 'str'
------------------------------------------------
Unknown Error - Code: X-5 occurred. This is probably my fault,
please a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

 Press Enter to Exit...https://www.youtube.com/watch?v=w6q0owZMfs0https://www.youtube.com/watch?v=w6q0owZMfs0
```

### Screenshots

Also restated (and it's started okay) and tried to update, and got this:
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/125238/e648263c-657a-4614-8fc1-3190ef1a5bd2)

**Comment by Firecul** [comment]
Looks like it could be something to do with your network connection imo. Maybe a pc/network restart?

**Comment by SoNickRND** [comment]
It's not a regular bug, it happens about once a week, I restart the browser sometimes and don't keep auth always saved.
