### ISSUE TITLE
'shutil' is not defined

### ISSUE THREAD

**Issue by PacoBell** [ThioJoe/YT-Spammer-Purge#1105]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

YT-Spammer-Purge-2.18.0-Beta3
Termux on Android 14

File "/storage/emulated/0/Download/YTSP/YT-Spammer-Purge-2.18.0-Beta3/Scripts/logging.py", line 769, in add_sample                                                        consoleWidth = utils.get_terminal_size()                               ^^^^^^^^^^^^^^^^^^^^^^^^^              File "/storage/emulated/0/Download/YTSP/YT-Spammer-Purge-2.18.0-Beta3/Scripts/utils.py", line 177, in get_terminal_size                                                   return shutil.get_terminal_size().columns                      ^^^^^^                                       NameError: name 'shutil' is not defined

You need to "import shutil" somewhere. That is all.

### Release version

2.18.0-Beta3

### Steps to reproduce

1. Run YTSP
2. Press Enter to display comments
3. Sadness

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
Traceback (most recent call last):
  File "/storage/emulated/0/Download/YTSP/YT-Spammer-Purge-2.18.0-Beta3/YTSpammerPurge.py", line 1721, in <module>
    main()
  File "/storage/emulated/0/Download/YTSP/YT-Spammer-Purge-2.18.0-Beta3/YTSpammerPurge.py", line 1698, in main      continueRunning = primaryInstance(miscData)                               ^^^^^^^^^^^^^^^^^^^^^^^^^           File "/storage/emulated/0/Download/YTSP/YT-Spammer-Purge-2.18.0-Beta3/YTSpammerPurge.py", line 1333, in primaryInstance                                                   logFileContents, logMode = logging.print_comments(current, config, scanVideoID, loggingEnabled, scanMode, logMode)                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                    File "/storage/emulated/0/Download/YTSP/YT-Spammer-Purge-2.18.0-Beta3/Scripts/logging.py", line 28, in print_comments                                                     j, commentsContents = print_prepared_comments(current, commentsContents, scanVideoID, list(current.matchedCommentsDict.keys()), j, loggingEnabled, scanMode, logMode, doWritePrint, matchReason="Filter Match")                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^               File "/storage/emulated/0/Download/YTSP/YT-Spammer-Purge-2.18.0-Beta3/Scripts/logging.py", line 332, in print_prepared_comments                                           add_sample(current, author_id_local, author, text, matchReason, matchedText, longestAuthorNameLength)         File "/storage/emulated/0/Download/YTSP/YT-Spammer-Purge-2.18.0-Beta3/Scripts/logging.py", line 769, in add_sample                                                        consoleWidth = utils.get_terminal_size()                               ^^^^^^^^^^^^^^^^^^^^^^^^^              File "/storage/emulated/0/Download/YTSP/YT-Spammer-Purge-2.18.0-Beta3/Scripts/utils.py", line 177, in get_terminal_size                                                   return shutil.get_terminal_size().columns                      ^^^^^^                                       NameError: name 'shutil' is not defined                 ------------------------------------------------
```

**Comment by Firecul** [comment]
It's a windows api according to [here](https://stackoverflow.com/questions/52686458/shutil-get-terminal-size-does-not-change) not really something easily imported on android.
Of course, I don't know code so I could be wrong

**Comment by PacoBell** [comment]
Naw, man, it's just part of Python. I literally just added the import one-liner to utils.py and it worked.

**Comment by Firecul** [comment]
> Naw, man, it's just part of Python. I literally just added the import one-liner to utils.py and it worked.


Fair enough

**Comment by therealOri** [comment]
To add onto this, logging.py and utils.py are the 2 files where shutil isn't imported.

**Comment by KitsuneNoBaka** [comment]
February 8 2025 and it's still here in v2.18.0-Beta3

Is this beta abandoned? Then why is still detected as new update?

Errors during startup:

`
Getting info about latest updates...
Loading filter file...

/home/user/Applications/YT-Spammer-Purge/Scripts/prepare_modes.py:391: SyntaxWarning: invalid escape sequence '\.'
  prepString = "\.("
/home/user/Applications/YT-Spammer-Purge/Scripts/prepare_modes.py:400: SyntaxWarning: invalid escape sequence '\/'
  prepString = prepString + ")\/"
/home/user/Applications/YT-Spammer-Purge/Scripts/confusablesCustom/__init__.py:46: SyntaxWarning: invalid escape sequence '\*'
  space_regex = "[\*_~|`\-\.]*" if include_character_padding else ''

Loading other assets..
`

Errors during work:

`
Comments ready to display. Also save a log file?  Highly Recommended! 
        (It even allows you to restore deleted comments later)

Save Log File (Recommended)? (y/n): y

Log file will be located at logs/Spam_Log_2025-02-08_11-25-16.txt

Press Enter to display comments...      TIP:  Widen this window now, and more comment sample text will be visible next!

-----------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/user/Applications/YT-Spammer-Purge/./YTSpammerPurge.py", line 1721, in <module>
    main()
  File "/home/user/Applications/YT-Spammer-Purge/./YTSpammerPurge.py", line 1698, in main
    continueRunning = primaryInstance(miscData)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Applications/YT-Spammer-Purge/./YTSpammerPurge.py", line 1333, in primaryInstance
    logFileContents, logMode = logging.print_comments(current, config, scanVideoID, loggingEnabled, scanMode, logMode)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Applications/YT-Spammer-Purge/Scripts/logging.py", line 28, in print_comments
    j, commentsContents = print_prepared_comments(current, commentsContents, scanVideoID, list(current.matchedCommentsDict.keys()), j, loggingEnabled, scanMode, logMode, doWritePrint, matchReason="Filter Match")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Applications/YT-Spammer-Purge/Scripts/logging.py", line 332, in print_prepared_comments
    add_sample(current, author_id_local, author, text, matchReason, matchedText, longestAuthorNameLength)
  File "/home/user/Applications/YT-Spammer-Purge/Scripts/logging.py", line 769, in add_sample
    consoleWidth = utils.get_terminal_size()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Applications/YT-Spammer-Purge/Scripts/utils.py", line 177, in get_terminal_size
    return shutil.get_terminal_size().columns
           ^^^^^^
NameError: name 'shutil' is not defined. Did you forget to import 'shutil'
------------------------------------------------
Error Message: name 'shutil' is not defined

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

 Press Enter to Exit...
`

**Comment by Firecul** [comment]
> Is this beta abandoned? Then why is still detected as new update?

Essentially the whole thing is at the moment until ThioJoe comes back to it. It has been over a year since the last update to the actual code it's self.

As @PacoBell,  @virophagesp and @therealOri have above, if you add `import shutils` into the `logging.py` and `utils.py` files (if you are using the python version) that should solve your problem. 

If you are using the exe however I'd stick with v2.17.1 personally.

**Comment by KitsuneNoBaka** [comment]
```
Importing Script Modules...
/home/user/Applications/YT-Spammer-Purge-2.18.0-Beta3/Scripts/utils.py:65: SyntaxWarning: invalid escape sequence '\{'
  keyboardSpecialChars = ("!@#$%^&*()_+-=[]\{\}|;':,./<>?`~")
Traceback (most recent call last):
  File "/home/user/Applications/YT-Spammer-Purge-2.18.0-Beta3/./YTSpammerPurge.py", line 45, in <module>
    import Scripts.auth as auth
  File "/home/user/Applications/YT-Spammer-Purge-2.18.0-Beta3/Scripts/auth.py", line 4, in <module>
    import Scripts.validation as validation
  File "/home/user/Applications/YT-Spammer-Purge-2.18.0-Beta3/Scripts/validation.py", line 5, in <module>
    import Scripts.utils as utils
  File "/home/user/Applications/YT-Spammer-Purge-2.18.0-Beta3/Scripts/utils.py", line 6, in <module>
    import shutils
ModuleNotFoundError: No module named 'shutils'
```

**Comment by Firecul** [comment]
> EDIT: ok, shutils is'n standard module, you must install it with PIP

It's been so long since I installed this I didn't think about that. 
It should probably be added to the `requirements.txt` if this ever gets an update then.
