### ISSUE TITLE
[Bug]: python error "EOF occurred in violation of protocol (_ssl.c:2426)" when reporting commetns

### ISSUE THREAD

**Issue by dnlweijers** [ThioJoe/YT-Spammer-Purge#1145]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to ... but then ...

### Release version

"{\"LatestRelease\": \"2024.12.22\", \"LastChecked\": \"2024.12.24.03.57\"}"

### Steps to reproduce

1.  Use tool on another account and follow the steps
2. To the point where you choose wether to only log or REPORT the comments, you choose REPORT, I get this error

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Press Enter to decide what to do with the rest...
How do you want to handle the rest of the comments (not ones you excluded)?
~~ Not Your Channel Mode: Only Reporting is Possible ~~
 > To report the comments for spam, type 'REPORT'.
 > To do nothing and only log, type 'NONE'

 (Not Case Sensitive) Input: REPORT





Traceback (most recent call last):[0 / 6] (In Groups of 50)
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1715, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1692, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1641, in primaryInstance
  File "Scripts\operations.py", line 1129, in delete_found_comments
  File "Scripts\operations.py", line 1086, in setStatus
  File "googleapiclient\_helpers.py", line 130, in positional_wrapper
  File "googleapiclient\http.py", line 923, in execute
  File "googleapiclient\http.py", line 222, in _retry_request
  File "googleapiclient\http.py", line 191, in _retry_request
  File "google_auth_httplib2.py", line 218, in request
  File "httplib2\__init__.py", line 1724, in request
  File "httplib2\__init__.py", line 1444, in _request
  File "httplib2\__init__.py", line 1367, in _conn_request
  File "http\client.py", line 1283, in request
  File "http\client.py", line 1329, in _send_request
  File "http\client.py", line 1278, in endheaders
  File "http\client.py", line 1038, in _send_output
  File "http\client.py", line 999, in send
  File "ssl.py", line 1237, in sendall
  File "ssl.py", line 1206, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2426)
------------------------------------------------
Error Message: EOF occurred in violation of protocol (_ssl.c:2426)
```

**Comment by Firecul** [comment]
Looks like a connection issue of some sort, does it still do this?
