### ISSUE TITLE
video not found error

### ISSUE THREAD

**Issue by thaynos** [ThioJoe/YT-Spammer-Purge#268]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to execute the script on this video but then it suddenly threw this error.

### Release version

2.4.2

### Steps to reproduce

1. launch app and choose 1st option for everything
2. when asked for yt link use this- [https://www.youtube.com/watch?v=_0MXhG1shEc]
3. wait for a while

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
Scanning 1/1: Minecraft Speedrunner VS 5 Hunters FINALE REMATCH

Traceback (most recent call last):| Replies Scanned: 6606 | Matches Found So Far: 26
  File "C:\Users\haade\Downloads\YT-Spammer-Purge-2.4.2\YT-Spammer-Purge-2.4.2\YouTubeSpammerPurge.py", line 2869, in <module>
    main()
  File "C:\Users\haade\Downloads\YT-Spammer-Purge-2.4.2\YT-Spammer-Purge-2.4.2\YouTubeSpammerPurge.py", line 2584, in main
    scan_video(youtube, miscData, currentUser, filterMode, filterSubMode, videoID, check_channel_id, inputtedSpammerChannelID, inputtedUsernameFilter, inputtedCommentTextFilter, regexPattern, videoTitle=videoTitle, showTitle=True, i=i)
  File "C:\Users\haade\Downloads\YT-Spammer-Purge-2.4.2\YT-Spammer-Purge-2.4.2\YouTubeSpammerPurge.py", line 2575, in scan_video
    nextPageToken = get_comments(youtube, miscData, currentUser, filterMode, filterSubMode, videoID, check_channel_id, nextPageToken, inputtedSpammerChannelID=inputtedSpammerChannelID, inputtedUsernameFilter=inputtedUsernameFilter, inputtedCommentTextFilter=inputtedCommentTextFilter, regexPattern=regexPattern)
  File "C:\Users\haade\Downloads\YT-Spammer-Purge-2.4.2\YT-Spammer-Purge-2.4.2\YouTubeSpammerPurge.py", line 306, in get_comments
    ).execute()
  File "C:\Users\haade\apps\python\lib\site-packages\googleapiclient\_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\haade\apps\python\lib\site-packages\googleapiclient\http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet%2C+replies&videoId=_0MXhG1shEc&maxResults=100&pageToken=QURTSl9pMVRzTDdVbzJLeWVaTm5lVGVFMG5xTGNyYks4TS1IeUh6SFdaNG52cDVqTms2NGdIR1ZPY0RfT1RtUUc3bkdfelhXLVJPVXpxTm01cDZRT2NZRnp2LXhkWTZOcUE%3D&fields=nextPageToken%2Citems%2Fsnippet%2FtopLevelComment%2Fid%2Citems%2Freplies%2Fcomments%2Citems%2Fsnippet%2FtotalReplyCount%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FvideoId%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FauthorChannelId%2Fvalue%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FauthorDisplayName%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FtextDisplay&textFormat=plainText&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter could not be found.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter could not be found.', 'domain': 'youtube.commentThread', 'reason': 'videoNotFound', 'location': 'videoId', 'locationType': 'parameter'}]">
------------------------------------------------
Error Message: <HttpError 404 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet%2C+replies&videoId=_0MXhG1shEc&maxResults=100&pageToken=QURTSl9pMVRzTDdVbzJLeWVaTm5lVGVFMG5xTGNyYks4TS1IeUh6SFdaNG52cDVqTms2NGdIR1ZPY0RfT1RtUUc3bkdfelhXLVJPVXpxTm01cDZRT2NZRnp2LXhkWTZOcUE%3D&fields=nextPageToken%2Citems%2Fsnippet%2FtopLevelComment%2Fid%2Citems%2Freplies%2Fcomments%2Citems%2Fsnippet%2FtotalReplyCount%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FvideoId%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FauthorChannelId%2Fvalue%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FauthorDisplayName%2Citems%2Fsnippet%2FtopLevelComment%2Fsnippet%2FtextDisplay&textFormat=plainText&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter could not be found.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter could not be found.', 'domain': 'youtube.commentThread', 'reason': 'videoNotFound', 'location': 'videoId', 'locationType': 'parameter'}]">
Status Code: 404
    Reason: videoNotFound
```

**Comment by ThioJoe** [comment]
Hm I tried it myself and it seems to be working. Does it work for you? The error message came from YouTube's side, and the video ID in the request that gave the error looks correct. So I think it was just a one-off bug.

**Comment by Firecul** [comment]
Seems to work fine for me also, I suspect you are correct with a one time bug 
  
  
![WindowsTerminal_Windows_PowerShell (2)](https://user-images.githubusercontent.com/34950371/147791894-5f867c60-b7e9-430e-a9f2-8fee7bb4a58a.png)
![WindowsTerminal_Windows_PowerShell (3)](https://user-images.githubusercontent.com/34950371/147791898-ac72611c-d8a7-45de-bf11-0641f5e73e17.png)

**Comment by ThioJoe** [comment]
Yea looks like a one-off
