### ISSUE TITLE
Can't complete authorization / Failed to parse: https://oauth2.googleapis.com/token

### ISSUE THREAD

**Issue by Clementwe** [ThioJoe/YT-Spammer-Purge#304]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

On first run trying to authorize, browser opens everything appears to run fine, after closing browser i get the error 

[!!!] Error: Failed to parse: https://oauth2.googleapis.com/token

I updated from 2.4.2 to 2.5.3 and it still does it.

### Release version

2.4.2 / 2.5.3

### Steps to reproduce

1. 
2. 
3. 

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
Loading YT Spammer Purge @ 2.5.3...

Please login using the browser window that opened just now.

Waiting for authorization. See message above.


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 382, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 2, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://oauth2.googleapis.com/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "YouTubeSpammerPurge.py", line 2362, in main
    youtube = get_authenticated_service() # Create authentication object
  File "YouTubeSpammerPurge.py", line 127, in get_authenticated_service
    creds = flow.run_local_server(port=0, authorization_prompt_message="Waiting for authorization. See message above.")
  File "/usr/local/lib/python3.8/dist-packages/google_auth_oauthlib/flow.py", line 477, in run_local_server
    self.fetch_token(authorization_response=authorization_response)
  File "/usr/local/lib/python3.8/dist-packages/google_auth_oauthlib/flow.py", line 286, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests_oauthlib/oauth2_session.py", line 336, in fetch_token
    r = self.request(
  File "/usr/local/lib/python3.8/dist-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 384, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://oauth2.googleapis.com/token
----------------
[!!!] Error: Failed to parse: https://oauth2.googleapis.com/token
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YouTube-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file. 
Press Enter to exit...
```

**Comment by ThioJoe** [comment]
Going based off this thread: https://github.com/psf/requests/issues/5476

Try updating the 'six' module in python and let me know if that works: https://pypi.org/project/six/

**Comment by Clementwe** [comment]
When i tried to upgrade it said it was already at latest version so i did a forced-reinstall now it works. Thank you
