### ISSUE TITLE
[Bug]: Program crashes, if you exclude all comments and try reporting

### ISSUE THREAD

**Issue by DaBlincx** [ThioJoe/YT-Spammer-Purge#377]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

i scanned a video i thought had many spam comments but it only found some youtube links and i excluded all listed comments and wanted to see, what happens, if i try reporting now but the program just crashed

### Release version

2.10.0

### Steps to reproduce

1.  scan a video
2.  exclude all listed comments
3.  report
4. watch it crash

### What platform are you seeing this problem on?

MacOS

### Relevant log output

```shell
Traceback (most recent call last):[0 / 0] (In Groups of 50)
  File "/Users/[USER]/Desktop/YT-Spammer-Purge-main/YouTubeSpammerPurge.py", line 4151, in <module>
    main()
  File "/Users/[USER]/Desktop/YT-Spammer-Purge-main/YouTubeSpammerPurge.py", line 4131, in main
    continueRunning = primaryInstance(miscData)
  File "/Users/[USER]/Desktop/YT-Spammer-Purge-main/YouTubeSpammerPurge.py", line 4100, in primaryInstance
    delete_found_comments(list(current.matchedCommentsDict), banChoice, deletionMode)
  File "/Users/[USER]/Desktop/YT-Spammer-Purge-main/YouTubeSpammerPurge.py", line 830, in delete_found_comments
    setStatus(commentsList)
  File "/Users/[USER]/Desktop/YT-Spammer-Purge-main/YouTubeSpammerPurge.py", line 796, in setStatus
    result = YOUTUBE.comments().markAsSpam(id=commentIDs).execute()
  File "/Users/[USER]/Library/Python/3.9/lib/python/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/[USER]/Library/Python/3.9/lib/python/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/comments/markAsSpam? returned "No filter selected. Expected one of: id". Details: "[{'message': 'No filter selected. Expected one of: id', 'domain': 'youtube.parameter', 'reason': 'missingRequiredParameter', 'location': 'parameters.', 'locationType': 'other'}]">
------------------------------------------------
Error Message: <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/comments/markAsSpam? returned "No filter selected. Expected one of: id". Details: "[{'message': 'No filter selected. Expected one of: id', 'domain': 'youtube.parameter', 'reason': 'missingRequiredParameter', 'location': 'parameters.', 'locationType': 'other'}]">
Status Code: 400
    Reason: missingRequiredParameter

An 'HttpError' was raised. This is sometimes caused by a remote server error. See the error info above.
If this keeps happening, consider posting a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
```

### Screenshots

```shell
<img width="1262" alt="ytspampurge_crash" src="https://user-images.githubusercontent.com/80812233/149308717-d0ef65fd-aabc-46b8-a99a-994eb213c266.png">

```

**Comment by ThioJoe** [comment]
I mean idk if this is a bug. But I'll probably add a message to handle if someone tries to do this

**Comment by ThioJoe** [comment]
Ok fixed with the latest commit in beta branch
