### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by Noob-A** [ThioJoe/YT-Spammer-Purge#381]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I have error from #58 contained no helpful info, so i have the same error as there

### Release version

2.10.0

### Steps to reproduce

1. I used guide to create a key
2. I pasted the key in `client_secrets.json`
3. I ran .exe file and i have the error

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Loading YT Spammer Purge @ 2.9.0...

Please login using the browser window that opened just now.



Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 2785, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 129, in get_authenticated_service
  File "google_auth_oauthlib\flow.py", line 202, in from_client_secrets_file
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 13 (char 12)
----------------
[!!!] Error: Extra data: line 1 column 13 (char 12)
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file.
Press Enter to exit...
```

**Comment by Firecul** [comment]
Does your browser open and ask you for authentication ok?

**Comment by ThioJoe** [comment]
no, you aren't supposed to paste the key into the file, you are supposed to download the file

**Comment by Noob-A** [comment]
Thank you.
