### ISSUE TITLE
[Bug]: Connection Error

### ISSUE THREAD

**Issue by Pumpkingames12** [ThioJoe/YT-Spammer-Purge#400]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was following the video instructions and once I got to the point where it would approve and create a token.pickle file it would take a minute and say there was a connection error.

### Release version

2.12.0

### Steps to reproduce

1. Download 2.12.0
2. Follow instructions up until you login with your google account you're using.
3. after it authorizes and creates a token.pickle it'll take a minute or 2 after and then the connection error occurs.

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Loading YT Spammer Purge @ 2.12.0...


Traceback (most recent call last):
  File "Scripts\auth.py", line 81, in first_authentication
  File "Scripts\auth.py", line 74, in get_authenticated_service
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\discovery.py", line 287, in build
  File "googleapiclient\discovery.py", line 420, in _retrieve_discovery_doc
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 922, in execute
  File "googleapiclient\http.py", line 221, in _retry_request
  File "googleapiclient\http.py", line 190, in _retry_request
  File "httplib2\__init__.py", line 1725, in request
  File "httplib2\__init__.py", line 1441, in _request
  File "httplib2\__init__.py", line 1363, in _conn_request
  File "httplib2\__init__.py", line 1153, in connect
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
----------------
[!!!] Error: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file.
Press Enter to exit...
```

**Comment by ThioJoe** [comment]
Hm this seems like an issue on google's side or your network side. Do yo have anything that might block the connection?

**Comment by Pumpkingames12** [comment]
A

**Comment by Pumpkingames12** [comment]
I figured it out, apparently the ad blocker and block tracker that I had on blocked the connection, after turning them off and opening the program up it works even when turning them all on again
