### ISSUE TITLE
I Haven't reached my Quota, but it says I have

### ISSUE THREAD

**Issue by Brayman30** [ThioJoe/YT-Spammer-Purge#466]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to open the app after setup but then the gave the output listed in the Relevant Log Output Section
I expected the app to run correctly, without errors.

### Release version

2.14.2

### Steps to reproduce

1. Follow Instructions in the [WalkThrough video](https://www.youtube.com/watch?v=c6ebWvay8dE), step-by-step
(Sorry, I don't know the specific way the issue originated)

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
===================== YOUTUBE SPAMMER PURGE v2.14.2 =====================
=========== https://github.com/ThioJoe/YT-Spammer-Purge ===========
================= Author: ThioJoe - YouTube.com/ThioJoe ================

Purpose: Lets you scan for spam comments and mass-delete them all at once

NOTE: It's probably better to scan individual videos, because you can scan all those comments,
      but scanning your entire channel must be limited and might miss older spam comments.
You will be shown the comments to confirm before they are deleted.
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1513, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 290, in main
  File "Scripts\auth.py", line 113, in get_current_user
  File "Scripts\auth.py", line 111, in fetch_user
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 937, in execute
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
------------------------------------------------
Error Message: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Status Code: 403
    Reason: quotaExceeded

Error: You have exceeded the YouTube API quota. To do more scanning you must wait until the quota resets.
 > There is a daily limit of 10,000 units/day, which works out to around reporting 10,000 comments/day.
 > You can check your quota by searching 'quota' in the google cloud console.
Solutions: Either wait until tomorrow, or create additional projects in the cloud console.
  > Read more about the quota limits for this app here: TJoe.io/api-limit-info

An 'HttpError' was raised. This is sometimes caused by a remote server error. See the error info above.
If this keeps happening, consider posting a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

Press Enter to Exit...
```

### Screenshots

![image](https://user-images.githubusercontent.com/33497147/152081952-71ef04fe-7712-47be-bf4d-bb94b730cdc1.png)
I can provide more screenshots of anything in Google Cloud if needed.

**Comment by ThioJoe** [comment]
Hm that's very weird, the actual YouTube API is what responded saying the quota is exceeded. Not sure why it would do that. I'll have to look up what might cause that.

**Comment by KendallDoesCoding** [comment]
@Brayman30 Can you make another project on the site and see if you face the same error again?

**Comment by Firecul** [comment]
The same thing seems to be happening to another user, he mentioned it after the original issue was closed in #437

**Comment by somecoderithink** [comment]
Well, I also got similar error (cuz the quota limit was exceeded when trying to report commments after scanning on MrBeast's latest video).
![Capture](https://user-images.githubusercontent.com/87126175/154420022-e782cf46-72f9-4ae2-8786-4676a20a1e2c.PNG)
Then I checked my quota at [](https://console.cloud.google.com/iam-admin/quotas)
![Captu2re](https://user-images.githubusercontent.com/87126175/154420143-8e291b87-484d-4546-8b59-ddc7b6b0fc94.PNG)
And...the quota limit was exceeded (by the way, version 2.16.0 of YT Spammer Purge)

**Comment by somecoderithink** [comment]
> ### Duplicate Issues
> * [x]  There are **no existing posts relating to my problem**
> * [ ]  There are **existing posts relating to my problem, but the solution given, doesn't work for me.**
> 
> ### What happened?
> Well, I was trying to open the app after setup but then the gave the output listed in the Relevant Log Output Section I expected the app to run correctly, without errors.
> 
> ### Release version
> 2.14.2
> 
> ### Steps to reproduce
> 1. Follow Instructions in the [WalkThrough video](https://www.youtube.com/watch?v=c6ebWvay8dE), step-by-step
>    (Sorry, I don't know the specific way the issue originated)
> 
> ### What platform are you seeing this problem on?
> Windows (.exe file)
> 
> ### Relevant log output
> ```shell
> ===================== YOUTUBE SPAMMER PURGE v2.14.2 =====================
> =========== https://github.com/ThioJoe/YT-Spammer-Purge ===========
> ================= Author: ThioJoe - YouTube.com/ThioJoe ================
> 
> Purpose: Lets you scan for spam comments and mass-delete them all at once
> 
> NOTE: It's probably better to scan individual videos, because you can scan all those comments,
>       but scanning your entire channel must be limited and might miss older spam comments.
> You will be shown the comments to confirm before they are deleted.
> Traceback (most recent call last):
>   File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1513, in <module>
>   File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 290, in main
>   File "Scripts\auth.py", line 113, in get_current_user
>   File "Scripts\auth.py", line 111, in fetch_user
>   File "googleapiclient\_helpers.py", line 131, in positional_wrapper
>   File "googleapiclient\http.py", line 937, in execute
> googleapiclient.errors.HttpError: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
> ------------------------------------------------
> Error Message: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
> Status Code: 403
>     Reason: quotaExceeded
> 
> Error: You have exceeded the YouTube API quota. To do more scanning you must wait until the quota resets.
>  > There is a daily limit of 10,000 units/day, which works out to around reporting 10,000 comments/day.
>  > You can check your quota by searching 'quota' in the google cloud console.
> Solutions: Either wait until tomorrow, or create additional projects in the cloud console.
>   > Read more about the quota limits for this app here: TJoe.io/api-limit-info
> 
> An 'HttpError' was raised. This is sometimes caused by a remote server error. See the error info above.
> If this keeps happening, consider posting a bug report on the GitHub issues page, and include the above error info.
> Short Link: TJoe.io/bug-report
> 
> Press Enter to Exit...
> ```
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/33497147/152081952-71ef04fe-7712-47be-bf4d-bb94b730cdc1.png) I can provide more screenshots of anything in Google Cloud if needed.

I figured it out (i think so), it is because when your quota was exceeded (according to YT Spammer Purge) but then it was near Midnight and then after a few minutes after was midnight then you checked at the cloud console and then you found out that you have not reached the limit but.. it is because the API quota resets every midnight (pacific ocean time).

**Comment by Brayman30** [comment]
> @Brayman30 Can you make another project on the site and see if you face the same error again?

Already tried that

**Comment by Brayman30** [comment]
> > ### Duplicate Issues
> > * [x]  There are **no existing posts relating to my problem**
> > * [ ]  There are **existing posts relating to my problem, but the solution given, doesn't work for me.**
> > 
> > ### What happened?
> > Well, I was trying to open the app after setup but then the gave the output listed in the Relevant Log Output Section I expected the app to run correctly, without errors.
> > 
> > ### Release version
> > 2.14.2
> > 
> > ### Steps to reproduce
> > 1. Follow Instructions in the [WalkThrough video](https://www.youtube.com/watch?v=c6ebWvay8dE), step-by-step
> >    (Sorry, I don't know the specific way the issue originated)
> > 
> > ### What platform are you seeing this problem on?
> > Windows (.exe file)
> > 
> > ### Relevant log output
> > ```shell
> > ===================== YOUTUBE SPAMMER PURGE v2.14.2 =====================
> > =========== https://github.com/ThioJoe/YT-Spammer-Purge ===========
> > ================= Author: ThioJoe - YouTube.com/ThioJoe ================
> > 
> > Purpose: Lets you scan for spam comments and mass-delete them all at once
> > 
> > NOTE: It's probably better to scan individual videos, because you can scan all those comments,
> >       but scanning your entire channel must be limited and might miss older spam comments.
> > You will be shown the comments to confirm before they are deleted.
> > Traceback (most recent call last):
> >   File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1513, in <module>
> >   File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 290, in main
> >   File "Scripts\auth.py", line 113, in get_current_user
> >   File "Scripts\auth.py", line 111, in fetch_user
> >   File "googleapiclient\_helpers.py", line 131, in positional_wrapper
> >   File "googleapiclient\http.py", line 937, in execute
> > googleapiclient.errors.HttpError: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
> > ------------------------------------------------
> > Error Message: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
> > Status Code: 403
> >     Reason: quotaExceeded
> > 
> > Error: You have exceeded the YouTube API quota. To do more scanning you must wait until the quota resets.
> >  > There is a daily limit of 10,000 units/day, which works out to around reporting 10,000 comments/day.
> >  > You can check your quota by searching 'quota' in the google cloud console.
> > Solutions: Either wait until tomorrow, or create additional projects in the cloud console.
> >   > Read more about the quota limits for this app here: TJoe.io/api-limit-info
> > 
> > An 'HttpError' was raised. This is sometimes caused by a remote server error. See the error info above.
> > If this keeps happening, consider posting a bug report on the GitHub issues page, and include the above error info.
> > Short Link: TJoe.io/bug-report
> > 
> > Press Enter to Exit...
> > ```
> > 
> > ### Screenshots
> > ![image](https://user-images.githubusercontent.com/33497147/152081952-71ef04fe-7712-47be-bf4d-bb94b730cdc1.png) I can provide more screenshots of anything in Google Cloud if needed.
> 
> I figured it out (i think so), it is because when your quota was exceeded (according to YT Spammer Purge) but then it was near Midnight and then after a few minutes after was midnight then you checked at the cloud console and then you found out that you have not reached the limit but.. it is because the API quota resets every midnight (pacific ocean time).

Okay, but what's the solution to this?

**Comment by somecoderithink** [comment]
> > > ### Duplicate Issues
> > > 
> > > * [x]   There are **no existing posts relating to my problem**
> > > * [ ]   There are **existing posts relating to my problem, but the solution given, doesn't work for me.**
> > > 
> > > ### What happened?
> > > Well, I was trying to open the app after setup but then the gave the output listed in the Relevant Log Output Section I expected the app to run correctly, without errors.
> > > ### Release version
> > > 2.14.2
> > > ### Steps to reproduce
> > > 
> > > 1. Follow Instructions in the [WalkThrough video](https://www.youtube.com/watch?v=c6ebWvay8dE), step-by-step
> > >    (Sorry, I don't know the specific way the issue originated)
> > > 
> > > ### What platform are you seeing this problem on?
> > > Windows (.exe file)
> > > ### Relevant log output
> > > ```shell
> > > ===================== YOUTUBE SPAMMER PURGE v2.14.2 =====================
> > > =========== https://github.com/ThioJoe/YT-Spammer-Purge ===========
> > > ================= Author: ThioJoe - YouTube.com/ThioJoe ================
> > > 
> > > Purpose: Lets you scan for spam comments and mass-delete them all at once
> > > 
> > > NOTE: It's probably better to scan individual videos, because you can scan all those comments,
> > >       but scanning your entire channel must be limited and might miss older spam comments.
> > > You will be shown the comments to confirm before they are deleted.
> > > Traceback (most recent call last):
> > >   File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1513, in <module>
> > >   File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 290, in main
> > >   File "Scripts\auth.py", line 113, in get_current_user
> > >   File "Scripts\auth.py", line 111, in fetch_user
> > >   File "googleapiclient\_helpers.py", line 131, in positional_wrapper
> > >   File "googleapiclient\http.py", line 937, in execute
> > > googleapiclient.errors.HttpError: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
> > > ------------------------------------------------
> > > Error Message: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
> > > Status Code: 403
> > >     Reason: quotaExceeded
> > > 
> > > Error: You have exceeded the YouTube API quota. To do more scanning you must wait until the quota resets.
> > >  > There is a daily limit of 10,000 units/day, which works out to around reporting 10,000 comments/day.
> > >  > You can check your quota by searching 'quota' in the google cloud console.
> > > Solutions: Either wait until tomorrow, or create additional projects in the cloud console.
> > >   > Read more about the quota limits for this app here: TJoe.io/api-limit-info
> > > 
> > > An 'HttpError' was raised. This is sometimes caused by a remote server error. See the error info above.
> > > If this keeps happening, consider posting a bug report on the GitHub issues page, and include the above error info.
> > > Short Link: TJoe.io/bug-report
> > > 
> > > Press Enter to Exit...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Screenshots
> > > ![image](https://user-images.githubusercontent.com/33497147/152081952-71ef04fe-7712-47be-bf4d-bb94b730cdc1.png) I can provide more screenshots of anything in Google Cloud if needed.
> > 
> > 
> > I figured it out (i think so), it is because when your quota was exceeded (according to YT Spammer Purge) but then it was near Midnight and then after a few minutes after was midnight then you checked at the cloud console and then you found out that you have not reached the limit but.. it is because the API quota resets every midnight (pacific ocean time).
> 
> Okay, but what's the solution to this?

To save your quota

**Comment by micziz** [comment]
Have you tried updating?

**Comment by EthanHindmarsh** [comment]
> Have you tried updating?

Comment before yours was a month ago, not sure this issue is active anymore
@Brayman30 any updates?

**Comment by virophagesp** [comment]
before I didnt have this issue

**Comment by virophagesp** [comment]
before I didn't have this
but today I am experiencing it

**Comment by virophagesp** [comment]
after waiting for the quota refresh it got solved
