### ISSUE TITLE
[Bug]: (Failure to run, MacOS, M1)

### ISSUE THREAD

**Issue by caretakerscurse** [ThioJoe/YT-Spammer-Purge#523]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Similar to #216 but on MacOS, manual install of tk does not fix.

Following the install instructions per [wiki](https://github.com/ThioJoe/YT-Spammer-Purge/wiki/MacOS-Instructions)

```
python3 --version
Python 3.9.10
```
```
grep "version =" YTSpammerPurge.py
version = "2.14.3"
```
```
   pip install -r requirements.txt       
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: google_api_python_client==2.33.0 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (2.33.0)
Requirement already satisfied: google_auth_oauthlib==0.4.6 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: protobuf==3.19.1 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (3.19.1)
Requirement already satisfied: colorama==0.4.4 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.4.4)
Requirement already satisfied: rtfunicode==2.0 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (2.0)
Requirement already satisfied: confusables==1.2.0 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (1.2.0)
Requirement already satisfied: certifi>=2021.10.8 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (2021.10.8)
Requirement already satisfied: six>=1.16.0 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (1.16.0)
Requirement already satisfied: python-Levenshtein>=0.12.2 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (0.12.2)
Requirement already satisfied: google-auth-httplib2>=0.1.0 in /opt/homebrew/lib/python3.9/site-packages (from google_api_python_client==2.33.0->-r requirements.txt (line 1)) (0.1.0)
Requirement already satisfied: httplib2<1dev,>=0.15.0 in /opt/homebrew/lib/python3.9/site-packages (from google_api_python_client==2.33.0->-r requirements.txt (line 1)) (0.20.4)
Requirement already satisfied: google-auth<3.0.0dev,>=1.16.0 in /opt/homebrew/lib/python3.9/site-packages (from google_api_python_client==2.33.0->-r requirements.txt (line 1)) (2.6.0)
Requirement already satisfied: uritemplate<5,>=3.0.0 in /opt/homebrew/lib/python3.9/site-packages (from google_api_python_client==2.33.0->-r requirements.txt (line 1)) (4.1.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=1.21.0 in /opt/homebrew/lib/python3.9/site-packages (from google_api_python_client==2.33.0->-r requirements.txt (line 1)) (2.5.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/homebrew/lib/python3.9/site-packages (from google_auth_oauthlib==0.4.6->-r requirements.txt (line 2)) (1.3.1)
Requirement already satisfied: setuptools in /opt/homebrew/lib/python3.9/site-packages (from python-Levenshtein>=0.12.2->-r requirements.txt (line 9)) (60.5.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.52.0 in /opt/homebrew/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (1.54.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /opt/homebrew/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (2.27.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /opt/homebrew/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (5.0.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/homebrew/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (4.8)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/homebrew/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (0.2.8)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /opt/homebrew/lib/python3.9/site-packages (from httplib2<1dev,>=0.15.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (3.0.7)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/homebrew/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google_auth_oauthlib==0.4.6->-r requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/homebrew/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.16.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/homebrew/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (2.0.11)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (3.3)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
```
```
   python3 YTSpammerPurge.py      
Traceback (most recent call last):
  File "/Users/ccam/Downloads/YT-Spammer-Purge-2.14.3/YTSpammerPurge.py", line 51, in <module>
    import Scripts.prepare_modes as modes
  File "/Users/ccam/Downloads/YT-Spammer-Purge-2.14.3/Scripts/prepare_modes.py", line 4, in <module>
    from Scripts.gui import *
  File "/Users/ccam/Downloads/YT-Spammer-Purge-2.14.3/Scripts/gui.py", line 14, in <module>
    from tkinter import Menu, TclError, Tk, Canvas, Entry, Text, Button, PhotoImage
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```
```
   pip install tk                 
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: tk in /opt/homebrew/lib/python3.9/site-packages (0.1.0)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
```
```
   python3 YTSpammerPurge.py
Traceback (most recent call last):
  File "/Users/ccam/Downloads/YT-Spammer-Purge-2.14.3/YTSpammerPurge.py", line 51, in <module>
    import Scripts.prepare_modes as modes
  File "/Users/ccam/Downloads/YT-Spammer-Purge-2.14.3/Scripts/prepare_modes.py", line 4, in <module>
    from Scripts.gui import *
  File "/Users/ccam/Downloads/YT-Spammer-Purge-2.14.3/Scripts/gui.py", line 14, in <module>
    from tkinter import Menu, TclError, Tk, Canvas, Entry, Text, Button, PhotoImage
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

### Release version

2.14.3

### Steps to reproduce

1.  python3 already installed via brew
2.  `pip install -r requirements.txt`
3.  `python3 YTSpammerPurge.py`

### What platform are you seeing this problem on?

MacOS

### Relevant log output

```shell
see `What happened?`
```

**Comment by Kurdakov** [comment]
as you are using brew then try
brew install python-tk

**Comment by oscrx** [comment]
I tried doing this but ran into the next bottleneck.
```
❯ pip install python-Levenshtein
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: python-Levenshtein in /opt/homebrew/lib/python3.9/site-packages (0.12.2)
Requirement already satisfied: setuptools in /opt/homebrew/lib/python3.9/site-packages (from python-Levenshtein) (60.5.0)
WARNING: You are using pip version 21.3.1; however, version 22.0.3 is available.
You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
❯ python3 YTSpammerPurge.py
Traceback (most recent call last):
  File "/Users/oscar/Documents/personal/YT-Spammer-Purge/YTSpammerPurge.py", line 50, in <module>
    import Scripts.operations as operations
  File "/Users/oscar/Documents/personal/YT-Spammer-Purge/Scripts/operations.py", line 15, in <module>
    from Levenshtein import ratio
  File "/opt/homebrew/lib/python3.9/site-packages/Levenshtein/__init__.py", line 1, in <module>
    from Levenshtein import _levenshtein
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/Levenshtein/_levenshtein.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.9/site-packages/Levenshtein/_levenshtein.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_levenshtein.cpython-39-darwin.so' (no such file), '/usr/lib/_levenshtein.cpython-39-darwin.so' (no such file)
 ~/Documents/personal/YT-Spammer-Purge │ on main         
```

Seems that the package python-Levenshtein does not have an arm64 binary available: [Link](https://pypi.org/project/python-Levenshtein/#files)

Maybe something is wrong with my Rosetta2 config, x86_64 binary's should be runnable...

**Comment by Kurdakov** [comment]
python-Levenshtein should compile from source to target architecture in case you have gcc and python-develop, so delete installed python-Levenshtein (I think it is: pip3 uninstall python-Leveshtein) download source code by link, install gcc and brew install python-develop, then 
python3 setup.py install from extracted source code from archive

**Comment by oscrx** [comment]
That fixed it for me.

**Comment by ThioJoe** [comment]
Ok gonna close this then since it's fixed

**Comment by caretakerscurse** [comment]
> as you are using brew then try brew install python-tk

This resolved it for me. Thank you all.
