### ISSUE TITLE
[Bug]: "ssl.SSLEOFError: EOF occurred in violation of protocol" during authorization

### ISSUE THREAD

**Issue by Dobby233Liu** [ThioJoe/YT-Spammer-Purge#537]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When I try to login, the authorization flow succeeds, but the app reports a SSL error. It may be a network issue on my side.

### Release version

2.14.3

### Steps to reproduce

1. Go through https://github.com/ThioJoe/YT-Spammer-Purge/wiki/Instructions:-Obtaining-an-API-Key and get secrets file
2. Start app
3. Try to login when the app prompts to

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Loading YT Spammer Purge @ 2.14.3...

Please login using the browser window that opened just now.

Waiting for authorization. See message above.


Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 364, in connect
  File "urllib3\connection.py", line 501, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Scripts\auth.py", line 86, in first_authentication
  File "Scripts\auth.py", line 74, in get_authenticated_service
  File "google_auth_oauthlib\flow.py", line 477, in run_local_server
  File "google_auth_oauthlib\flow.py", line 286, in fetch_token
  File "requests_oauthlib\oauth2_session.py", line 336, in fetch_token
  File "requests_oauthlib\oauth2_session.py", line 515, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
----------------
[!!!] Error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file.
Press Enter to exit...
```

**Comment by Dobby233Liu** [comment]
Configured the proxy I use, still no luck

**Comment by Dobby233Liu** [comment]
Actually, I tried to remove my HTTPS_PROXY env var, but now I get a timeout message
![image](https://user-images.githubusercontent.com/28653235/152483053-d974c145-ad3a-4ded-9e6d-65c537f6c997.png)

**Comment by Dobby233Liu** [comment]
https://github.com/psf/requests/issues/3006#issuecomment-186265369 interesting

**Comment by Dobby233Liu** [comment]
Run with script version, succeed

**Comment by Dobby233Liu** [comment]
My deps now
```
Package                  Version
------------------------ ---------
cachetools               5.0.0
certifi                  2021.10.8
cffi                     1.15.0
charset-normalizer       2.0.11
colorama                 0.4.4
confusables              1.2.0
cryptography             36.0.1
google-api-core          2.5.0
google-api-python-client 2.33.0
google-auth              2.6.0
google-auth-httplib2     0.1.0
google-auth-oauthlib     0.4.6
googleapis-common-protos 1.54.0
httplib2                 0.20.4
idna                     3.3
ndg-httpsclient          0.5.1
oauthlib                 3.2.0
pip                      21.2.4
protobuf                 3.19.1
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.21
pyOpenSSL                22.0.0
pyparsing                3.0.7
python-Levenshtein       0.12.2
requests                 2.27.1
requests-oauthlib        1.3.1
rsa                      4.8
rtfunicode               2.0
setuptools               58.1.0
six                      1.16.0
uritemplate              4.1.1
urllib3                  1.26.8
```

**Comment by rachmadaniHaryono** [comment]
maybe put python version and windows version to help other who have similar setup

**Comment by Dobby233Liu** [comment]
Windows version
![image](https://user-images.githubusercontent.com/28653235/152486657-d4fd8592-45c5-439a-97fa-6a4ba85a2512.png)
Python version
> Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32

**Comment by ThioJoe** [comment]
Ok since it was resolved with installing the script version I'll close this, and just instruct future users about it
