### ISSUE TITLE
[Bug][User Error]: Entering the Log Path on the New List or Continue prompt (X-2, Z-3)

### ISSUE THREAD

**Issue by lloyddunamis** [ThioJoe/YT-Spammer-Purge#576]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Involved option: `7. Remove comments using a pre-existing list or log file`

I uhh...went ahead of myself and entered the log path on the prompt "Use new comment list, or continue where you left off with another list?".
I'm aware it's user error though, but just in case it might cause a headache in the long run or something...

Hmm... or it can prolly make it as like, if it detects an filename/path or if the response is not `2` for "Continuing from a list", it can assume the user wants to start from a new list...if that isn't too much to do.

### Release version

2.14.3, 2.15.0-Beta1 to 2.15.0-Beta4

### Steps to reproduce

**2. Hide**
1. Scanning Option `7. Remove comments using a pre-existing list or log file`
2. When asked if "New List" or "Continue With a List": drag a log (or I guess any file) or input the log filename to it.
    Program skips the actual log name/path prompt.
3. `2. Hide`
Error X-2 should occur.

**1. Delete**
   1-2. _Same as above._
   3. `1. Delete`
   4. Either Y/N
Error Z-3 should occur.

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
[2.15.0-Beta4]
**2. Hide** 
Selection (1 or 2): 2
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1600, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1577, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 887, in primaryInstance
  File "Scripts\prepare_modes.py", line 685, in delete_comment_list
UnboundLocalError: local variable 'removalList' referenced before assignment
------------------------------------------------
Error Message: local variable 'removalList' referenced before assignment

Error - Code: X-2 occurred. This is almost definitely my fault and requires patching (big bruh moment)


================================================================================
**1. Delete**
Selection (1 or 2): 1

Also ban the commenters? (y/n): n
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1600, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1577, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 887, in primaryInstance
  File "Scripts\prepare_modes.py", line 677, in delete_comment_list
AttributeError: 'bool' object has no attribute 'lower'
------------------------------------------------
Error Message: 'bool' object has no attribute 'lower'

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
```

### Screenshots

[2.15.0-Beta4] **Hide**
![image](https://user-images.githubusercontent.com/6012867/152667992-94e5f130-09d2-4e4a-80f1-13e7202dcfea.png)

[2.15.0-Beta4] **Delete**
![image](https://user-images.githubusercontent.com/6012867/152668297-dfdfddf0-bafb-4fdc-9742-82c44bd8c9bc.png)

**Comment by ThioJoe** [comment]
Hm ok I'll add a check for it

**Comment by ThioJoe** [comment]
Added a quick check with https://github.com/ThioJoe/YT-Spammer-Purge/commit/d8d757b2e2a84a2b1689ed3552fe8163263262df for the next release
