### ISSUE TITLE
[Bug]: ValueErrir: list.remove(x): x  not in list

### ISSUE THREAD

**Issue by Jakre73** [ThioJoe/YT-Spammer-Purge#596]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When I'm trying to scan a specific video it always fails after around 1.250 of 35.000 comments with the error code "Unknown Error - Code: Z-3". The output of the program can be seen in the attached screenshot below. URL to the video that I've tried to scan: https://www.youtube.com/watch?v=YQ_xWvX1n9g

### Release version

2.15.0

### Steps to reproduce

1. Start the program and start the scan for a single video (https://www.youtube.com/watch?v=YQ_xWvX1n9g)
2. Scan mode: Auto-Smart Mode
3. Scan in "Not You Channel Mode"
4. Scan always fails after around 1.250 scanned comments (tried multiple times)
5. Following output was shown after it failed:
![image](https://user-images.githubusercontent.com/36055573/152888640-9aaee658-1dcf-4f83-b597-16ed01afcc7f.png)

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
> At any prompt, enter 'X' to return here
> Enter 'Q' now to quit


-------------------------------- Scanning Options --------------------------------
      1. Scan specific videos
      2. Scan recent videos for a channel
      3. Scan recent comments across your Entire Channel
      4. Scan a specific community post (Experimental)
      5. Scan recent community posts for a channel (Experimental)

--------------------------------- Other Options ----------------------------------
      6. Create your own config file(s) to run the program with pre-set settings
      7. Remove comments using a pre-existing list or log file
      8. Recover deleted comments using log file
      9. Check & Download Updates

Choice (1-9): 1

Enter a list of Video Links or Video IDs to scan, separated by commas.
 > Note: All videos must be from the same channel.

Enter here: https://www.youtube.com/watch?v=YQ_xWvX1n9g

Chosen Videos:
 1. Line Goes Up – The Problem With NFTs

NOTE: This is not your video. Enabling 'Not Your Channel Mode'. You can report spam comments, but not delete them.
Total number of comments to scan: 35901

Is this video list correct? (y/n): y

-------------------------------------------------------
~~~~~~~~~~~ Choose how to identify spammers ~~~~~~~~~~~
-------------------------------------------------------
 1. (RECOMMENDED): Auto-Smart Mode: Automatically detects multiple spammer techniques
 2. Sensitive-Smart Mode: Much more likely to catch all spammers, but with significantly more false positives
 3. Enter Spammer's channel ID(s) or link(s)
 4. Scan usernames for criteria you choose
 5. Scan comment text for criteria you choose
 6. Scan both usernames and comment text for criteria you choose
 7. ASCII Mode: Scan usernames for ANY non-ASCII special characters (May cause collateral damage!)
 Note: With 'Not Your Channel Mode' enabled, you can only report matched comments while using 'Auto-Smart Mode'
 or 'Sensitive-Smart Mode'.

Choice (1-7): 1

----------------------------------------------- Auto-Smart Mode -----------------------------------------------
~~~ This mode is a spammer's worst nightmare. It automatically scans for multiple spammer techniques ~~~

 > Extremely low (near 0%) false positives
 > Detects whatsapp scammers and '18+ spam' bots
 > Easily cuts through look-alike characters and obfuscations, including impersonating usernames
 > NOTE: This mode prioritizes a VERY low false positive rate, at the cost of occasionally missing some spammers.



------------------------------------------------------------------------------
(Note: If the program appears to freeze, try right clicking within the window)

                          --- Scanning ---

Scanning 1/1: Line Goes Up – The Problem With NFTs

Traceback (most recent call last):ents Scanned: 1247 | Replies Scanned: 3070 | Matches Found So Far: 267
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1612, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1589, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1151, in primaryInstance
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1134, in scan_video
  File "Scripts\operations.py", line 123, in get_comments
  File "Scripts\operations.py", line 248, in get_replies
  File "Scripts\operations.py", line 365, in check_spam_threads
  File "Scripts\operations.py", line 344, in remove_ignore
ValueError: list.remove(x): x not in list
------------------------------------------------
Error Message: list.remove(x): x not in list

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

 Press Enter to Exit...
```

**Comment by Jakre73** [comment]
![image](https://user-images.githubusercontent.com/36055573/152889214-6c0fde0f-7fce-402e-8b9a-cfcfef39af9c.png)
API limit of 10k scans was not reached yet

**Comment by Firecul** [comment]
> ![image](https://user-images.githubusercontent.com/36055573/152889214-6c0fde0f-7fce-402e-8b9a-cfcfef39af9c.png) API limit of 10k scans was not reached yet

Yip that's not a factor, I crash in a very similar place.

![WindowsTerminal_Windows_PowerShell (18)](https://user-images.githubusercontent.com/34950371/152900529-bd539edd-aea0-44af-9def-e300d6472418.png)

**Comment by ThioJoe** [comment]
Ok should be fixed with the new release
