### ISSUE TITLE
Connection Timeout Error

### ISSUE THREAD

**Issue by somecoderithink** [ThioJoe/YT-Spammer-Purge#651]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I just opened YT Spammer Purge then it gave a long error and then it said "try deleting the token.pickle file". 
Then i closed it and then deleted token.pickle then opened yt spammer purge and logged in but then it failed.

### Release version

2.15.1

### Steps to reproduce

1.  Make sure you did all that api stuff
2. Open the app

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 358, in connect
  File "urllib3\connection.py", line 179, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001EB37702FB0>, 'Connection to oauth2.googleapis.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001EB37702FB0>, 'Connection to oauth2.googleapis.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Scripts\auth.py", line 86, in first_authentication
  File "Scripts\auth.py", line 74, in get_authenticated_service
  File "google_auth_oauthlib\flow.py", line 477, in run_local_server
  File "google_auth_oauthlib\flow.py", line 286, in fetch_token
  File "requests_oauthlib\oauth2_session.py", line 336, in fetch_token
  File "requests_oauthlib\oauth2_session.py", line 515, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 504, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001EB37702FB0>, 'Connection to oauth2.googleapis.com timed out. (connect timeout=None)'))
----------------
[!!!] Error: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001EB37702FB0>, 'Connection to oauth2.googleapis.com timed out. (connect timeout=None)'))
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file.
```

**Comment by ThioJoe** [comment]
Several users have reported the same thing happening out of the blue after it working before. I think it's something on YouTube's back end. Some have said it might be working now? I'd just wait a few hours and try again

**Comment by Firecul** [comment]
I must be just getting lucky then, I've not had this issue even once yet

**Comment by guywhoreportsissues** [comment]
> Several users have reported the same thing happening out of the blue after it working before. I think it's something on YouTube's back end. Some have said it might be working now? I'd just wait a few hours and try again. It seems to have started on the weekend so hopefully they'll be able to work on the API now that the work week has started.

Fixed by Google. Closed my issue.

**Comment by somecoderithink** [comment]
idk, how it started to work.
![Capture](https://user-images.githubusercontent.com/87126175/154042117-93f80785-a8c8-4f71-b75f-95041e92308c.PNG)

**Comment by somecoderithink** [comment]
> Is your firewall, or some other network filter, blocking its connection to `googleapis.com`

Nope, nothing was blocking googleapis.com
