### ISSUE TITLE
[Bug]: Recent Community Post KeyError

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#653]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I tried scanning recent community posts from a channel but crashed with an X-4.
It seems to fail while checking for duplicates in auto mode

### Release version

v2.16.0-Beta2

### Steps to reproduce

1. Scan recent community posts
2. I used `https://www.youtube.com/channel/UCbuJJ79M4Syuict0R7C2MTA` but I don't think that'll be important.
3. 1 recent post
4. Auto-Smart mode

### What platform are you seeing this problem on?

Windows (.py script)

### Relevant log output

```shell
Traceback (most recent call last):% ]   (Can be disabled & customized in config)
  File "C:\Users\firec\Documents\GitHub\YT-Spammer-Purge\YTSpammerPurge.py", line 2358, in <module>
    main()
  File "C:\Users\firec\Documents\GitHub\YT-Spammer-Purge\YTSpammerPurge.py", line 2336, in main
    continueRunning = primaryInstance(miscData)
  File "C:\Users\firec\Documents\GitHub\YT-Spammer-Purge\YTSpammerPurge.py", line 1560, in primaryInstance
    scan_community_post(
  File "C:\Users\firec\Documents\GitHub\YT-Spammer-Purge\YTSpammerPurge.py", line 1530, in scan_community_post
    operations.check_duplicates(
  File "C:\Users\firec\Documents\GitHub\YT-Spammer-Purge\Scripts\operations.py", line 846, in check_duplicates
    add_spam(
  File "C:\Users\firec\Documents\GitHub\YT-Spammer-Purge\Scripts\operations.py", line 705, in add_spam
    originalCommentID = currentCommentDict["originalCommentID"]
KeyError: 'originalCommentID'
------------------------------------------------
Unknown Error - Code: X-4 occurred. This is probably my fault,
please a bug report on the GitHub issues page, and include the above error info.
```

### Screenshots

![WindowsTerminal_Windows_PowerShell (26)](https://user-images.githubusercontent.com/34950371/153966586-ceb1afe1-2e71-4bde-a43a-c59c83758455.png)

**Comment by ThioJoe** [comment]
Should be fixed in the new 2.16.0-Beta3 release
