### ISSUE TITLE
List object has no attribute lower

### ISSUE THREAD

**Issue by nhoffudel** [ThioJoe/YT-Spammer-Purge#662]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I'm running your (excellent) program on Windows from the .exe with full ownership of the folder. It worked last night after I installed it but today it has an error with a stack trace to your computer. It forces an exit after the error occurs. I tried running it as admin but the result is the same. It finds 10 spam comments and throws the error.
![image](https://user-images.githubusercontent.com/14076667/154167699-6b0e197d-2fce-4d1b-be0f-4df685cf2b78.png)

Traceback (most recent call last):ents Scanned: 567 | Replies Scanned: 95 | Matches Found So Far: 10
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1670, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1647, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1209, in primaryInstance
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1192, in scan_video
  File "Scripts\operations.py", line 120, in get_comments
  File "Scripts\operations.py", line 910, in check_against_filter
  File "Scripts\operations.py", line 844, in findObf
AttributeError: 'list' object has no attribute 'lower'
------------------------------------------------
Error Message: 'list' object has no attribute 'lower'

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.

### Steps to reproduce

I ran this with the recommended normal options. I had logged in with my YT burner account last night and it remembered as such.
I pasted a specific Doug DeMuro video link https://www.youtube.com/watch?v=1F0ryJApP0A. It enabled not your video mode.
Option 1 auto scan, hit enter, and it scanned a few hundred comments before throwing the error at 10 spam comments. I have run it several times with and without admin and it consistently throws an error at 10.

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Scanning 1/1: The New 2022 Volkswagen GTI Is Terrific, But Flawed

Traceback (most recent call last):ents Scanned: 575 | Replies Scanned: 96 | Matches Found So Far: 10
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1670, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1647, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1209, in primaryInstance
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1192, in scan_video
  File "Scripts\operations.py", line 120, in get_comments
  File "Scripts\operations.py", line 910, in check_against_filter
  File "Scripts\operations.py", line 844, in findObf
AttributeError: 'list' object has no attribute 'lower'
------------------------------------------------
Error Message: 'list' object has no attribute 'lower'

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
```

### Screenshots

![image](https://user-images.githubusercontent.com/14076667/154167871-2d949494-2078-4615-a8dd-2d6aa181c54e.png)

**Comment by rachmadaniHaryono** [comment]
Duplicate of #654

**Comment by Firecul** [comment]
> Duplicate of #654?

That bug was fixed in Beta3. Which I now see @nhoffudel isn't using. 

@nhoffudel can you try the [new beta3](https://github.com/ThioJoe/YT-Spammer-Purge/releases/tag/v2.16.0-Beta3) exe and see if that works ok for you?

**Comment by ThioJoe** [comment]
Yea that one should be fixed in 2.16.3, try that

**Comment by nhoffudel** [comment]
Success, and apologies for missing #654. I must not have searched the right keywords and I didn't think to check for a new version. I'm not used to releases coming so quickly. Keep up the great work!

**Comment by Firecul** [comment]
> Success, and apologies for missing https://github.com/ThioJoe/YT-Spammer-Purge/issues/654. I must not have searched the right keywords and I didn't think to check for a new version.

Don't worry about it, it's hard to keep up with let alone when starting from nearly scratch.
