### ISSUE TITLE
[Bug]: Can't login: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by j5155** [ThioJoe/YT-Spammer-Purge#761]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to run YT Spammer Purge, which prompted me to login, but then when I finished logging in it gave me this error:
`Loading YT Spammer Purge @ 2.16.6...

Please login using the browser window that opened just now.

Waiting for authorization. See message above.

Traceback (most recent call last):
  File "/home/j5155/Git/YT-Spammer-Purge/Scripts/auth.py", line 86, in first_authentication
    YOUTUBE = get_authenticated_service() # Create authentication object
  File "/home/j5155/Git/YT-Spammer-Purge/Scripts/auth.py", line 74, in get_authenticated_service
    creds = flow.run_local_server(port=0, authorization_prompt_message="Waiting for authorization. See message above.")
  File "/home/j5155/.local/lib/python3.9/site-packages/google_auth_oauthlib/flow.py", line 476, in run_local_server
    authorization_response = wsgi_app.last_request_uri.replace("http", "https")
AttributeError: 'NoneType' object has no attribute 'replace'
----------------
[!!!] Error: 'NoneType' object has no attribute 'replace'
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file. 
Press Enter to exit...
`

### Release version

2.16.6

### Steps to reproduce

Unknown, but for me it was:
1. Start YT-Spammer-Purge
2. Attempt to login in the browser window it opens
3. See error

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
Loading YT Spammer Purge @ 2.16.6...

Please login using the browser window that opened just now.

Waiting for authorization. See message above.


Traceback (most recent call last):
  File "/home/j5155/Git/YT-Spammer-Purge/Scripts/auth.py", line 86, in first_authentication
    YOUTUBE = get_authenticated_service() # Create authentication object
  File "/home/j5155/Git/YT-Spammer-Purge/Scripts/auth.py", line 74, in get_authenticated_service
    creds = flow.run_local_server(port=0, authorization_prompt_message="Waiting for authorization. See message above.")
  File "/home/j5155/.local/lib/python3.9/site-packages/google_auth_oauthlib/flow.py", line 476, in run_local_server
    authorization_response = wsgi_app.last_request_uri.replace("http", "https")
AttributeError: 'NoneType' object has no attribute 'replace'
----------------
[!!!] Error: 'NoneType' object has no attribute 'replace'
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file. 
Press Enter to exit...
```

**Comment by DinhHuy2010** [comment]
when you login, does say "The authentication flow has completed. You may close this window." or network error?

**Comment by ThioJoe** [comment]
This seems to be the same issue as #275 and probably has to do with the browser. Try the suggestion in this post which worked for others: https://github.com/googleapis/google-auth-library-python-oauthlib/issues/69#issuecomment-834720945

**Comment by j5155** [comment]
I use Firefox similar to other people having this issue, but temporarily using a Chromium-based browser fixed it; seems like you might want to put info somewhere about Firefox being incompatible (or find out why).

**Comment by TechStudent11** [comment]
> I use Firefox similar to other people having this issue, but temporarily using a Chromium-based browser fixed it. However, it seems like you might want to put info somewhere about Firefox being incompatible (or find out why).

Not sure if you've tried this, but I found this help thread on the Mozilla Support page: https://support.mozilla.org/en-US/questions/1312203
