### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'token.pickle'

### ISSUE THREAD

**Issue by A-Metal-Penguin** [ThioJoe/YT-Spammer-Purge#805]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to login to the app for the first time but then got this error (EDIT: Forgot to say I tried using Brave, Chrome and even 🤢Edge🤮 as my default Browsers and still got the error):
```
Loading YT Spammer Purge @ 2.16.9...

Please login using the browser window that opened just now.

Waiting for authorization. See message above.
[OK] Authorization Complete.


Traceback (most recent call last):
  File "Scripts\auth.py", line 86, in first_authentication
  File "Scripts\auth.py", line 77, in get_authenticated_service
PermissionError: [Errno 13] Permission denied: 'token.pickle'
----------------
[!!!] Error: [Errno 13] Permission denied: 'token.pickle'
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file.
Press Enter to exit...
```

### Release version

YOUTUBE SPAMMER PURGE VERSION 2.16.9

### Steps to reproduce

🤔

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Loading YT Spammer Purge @ 2.16.9...

Please login using the browser window that opened just now.

Waiting for authorization. See message above.
[OK] Authorization Complete.


Traceback (most recent call last):
  File "Scripts\auth.py", line 86, in first_authentication
  File "Scripts\auth.py", line 77, in get_authenticated_service
PermissionError: [Errno 13] Permission denied: 'token.pickle'
----------------
[!!!] Error: [Errno 13] Permission denied: 'token.pickle'
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file.
Press Enter to exit...
```

**Comment by A-Metal-Penguin** [comment]
Perhaps I did this too quickly? It's working now. I did run as administrator. IDK 🤷‍♂️
