### ISSUE TITLE
[Bug]: (Enter short, one sentence summary of bug here)

### ISSUE THREAD

**Issue by TheMythologist** [ThioJoe/YT-Spammer-Purge#813]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

`tkinter` doesn't come packaged together with [the requirements file](requirements.txt)

### Steps to reproduce

1. Install python requirements via `pip install -r requirements.txt`
1. Run YTSpammerPurge.py via `python YTSpammerPurge.py`

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
user@ubuntu:~/Documents/YT-Spammer-Purge$ pip3 install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Collecting google_api_python_client==2.33.0
  Downloading google_api_python_client-2.33.0-py2.py3-none-any.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 5.2 MB/s eta 0:00:00
Collecting google_auth_oauthlib==0.4.6
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting protobuf==3.19.1
  Downloading protobuf-3.19.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 5.1 MB/s eta 0:00:00
Requirement already satisfied: colorama==0.4.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (0.4.4)
Collecting rtfunicode==2.0
  Downloading rtfunicode-2.0-py3-none-any.whl (4.2 kB)
Collecting certifi>=2021.10.8
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.2/149.2 KB 4.0 MB/s eta 0:00:00
Requirement already satisfied: six>=1.16.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (1.16.0)
Collecting python-Levenshtein>=0.12.2
  Downloading python-Levenshtein-0.12.2.tar.gz (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 KB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting regex>=2022.1.18
  Downloading regex-2022.4.24-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (763 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 763.2/763.2 KB 4.5 MB/s eta 0:00:00
Requirement already satisfied: google-auth<3.0.0dev,>=1.16.0 in /home/kx/.local/lib/python3.9/site-packages (from google_api_python_client==2.33.0->-r requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: httplib2<1dev,>=0.15.0 in /usr/lib/python3/dist-packages (from google_api_python_client==2.33.0->-r requirements.txt (line 1)) (0.18.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=1.21.0 in /home/kx/.local/lib/python3.9/site-packages (from google_api_python_client==2.33.0->-r requirements.txt (line 1)) (2.0.1)
Collecting uritemplate<5,>=3.0.0
  Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Collecting google-auth-httplib2>=0.1.0
  Downloading google_auth_httplib2-0.1.0-py2.py3-none-any.whl (9.3 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: setuptools in /home/kx/.local/lib/python3.9/site-packages (from python-Levenshtein>=0.12.2->-r requirements.txt (line 8)) (59.2.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /home/kx/.local/lib/python3.9/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (1.53.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/lib/python3/dist-packages (from google-api-core<3.0.0dev,>=1.21.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (2.25.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/kx/.local/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/kx/.local/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (4.2.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/kx/.local/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (4.7.2)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google_auth_oauthlib==0.4.6->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/kx/.local/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.16.0->google_api_python_client==2.33.0->-r requirements.txt (line 1)) (0.4.8)
Building wheels for collected packages: python-Levenshtein
  Building wheel for python-Levenshtein (setup.py) ... done
  Created wheel for python-Levenshtein: filename=python_Levenshtein-0.12.2-cp39-cp39-linux_x86_64.whl size=160452 sha256=f04c80b472e73afbac7aad3501e8dad12da8073bdb793c2414b8fd5ba8ba58b9
  Stored in directory: /home/kx/.cache/pip/wheels/46/4a/6c/164a1d9dd67c82d208f19d869ad0a517a0c5a6117f608c53e6
Successfully built python-Levenshtein
Installing collected packages: certifi, uritemplate, rtfunicode, requests-oauthlib, regex, python-Levenshtein, protobuf, google_auth_oauthlib, google-auth-httplib2, google_api_python_client
  Attempting uninstall: regex
    Found existing installation: regex 2021.11.10
    Uninstalling regex-2021.11.10:
      Successfully uninstalled regex-2021.11.10
Successfully installed certifi-2021.10.8 google-auth-httplib2-0.1.0 google_api_python_client-2.33.0 google_auth_oauthlib-0.4.6 protobuf-3.19.1 python-Levenshtein-0.12.2 regex-2022.4.24 requests-oauthlib-1.3.1 rtfunicode-2.0 uritemplate-4.1.1

user@ubuntu:~/Documents/YT-Spammer-Purge$ python3 YTSpammerPurge.py
Importing Script Modules...
Traceback (most recent call last):
  File "/home/kx/Documents/YT-Spammer-Purge/YTSpammerPurge.py", line 51, in <module>
    import Scripts.prepare_modes as modes
  File "/home/kx/Documents/YT-Spammer-Purge/Scripts/prepare_modes.py", line 4, in <module>
    from Scripts.gui import *
  File "/home/kx/Documents/YT-Spammer-Purge/Scripts/gui.py", line 14, in <module>
    from tkinter import Menu, TclError, Tk, Canvas, Entry, Text, Button, PhotoImage
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by TheMythologist** [comment]
My bad, seems I didn't install tkinter via  `sudo apt-get install python3-tk`, closing the issue
