### ISSUE TITLE
[Bug]: module Scripts has no attribute auth

### ISSUE THREAD

**Issue by arcreigh** [ThioJoe/YT-Spammer-Purge#869]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Fresh installation results in the following stack trace.

python3 YTSpammerPurge.py
Importing Script Modules...
Traceback (most recent call last):
  File "YTSpammerPurge.py", line 45, in <module>
    import Scripts.auth as auth
  File "/home/arcreigh/YT-Spammer-Purge/Scripts/auth.py", line 4, in <module>
    import Scripts.validation as validation
  File "/home/arcreigh/YT-Spammer-Purge/Scripts/validation.py", line 4, in <module>
    import Scripts.auth as auth
AttributeError: module 'Scripts' has no attribute 'auth'

### Release version

v2.16.9

### Steps to reproduce

Fresh installation on WSL Ubuntu 18.04 
chmod +x YTSpammerPurge.py
python3 YTSpammerPurge.py

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
python3 YTSpammerPurge.py
Importing Script Modules...
Traceback (most recent call last):
  File "YTSpammerPurge.py", line 45, in <module>
    import Scripts.auth as auth
  File "/home/arcreigh/YT-Spammer-Purge/Scripts/auth.py", line 4, in <module>
    import Scripts.validation as validation
  File "/home/arcreigh/YT-Spammer-Purge/Scripts/validation.py", line 4, in <module>
    import Scripts.auth as auth
AttributeError: module 'Scripts' has no attribute 'auth'
```

**Comment by Firecul** [comment]
Have you tried any other method to use this or only WSL? I can't actually test that to help you.

**Comment by Firecul** [comment]
In stock windows, I needed to install Microsoft C++ Build Tools so Levenshtein could be built then ran the `python3 pip install -m requirements.txt` again and everything works fine. I'd assume it's a similar problem.

**Comment by arcreigh** [comment]
Not sure myself, looking at the code the path is there for the import it should be able to see that auth exists as it is there. I can try the pip install requirements.

**Comment by ThioJoe** [comment]
Wondering if this has since worked itself out, considering WSL is in full release now.

It seems to suggest some kind of filesystem related thing, or python's interaction with it. Since it basically isn't seeing the auth script. But it's weird that that only happens in the validation script. So it's not even the first script to be imported, the others which are in the same exact folder, and it's not even the first time Scripts.auth is imported.
