### ISSUE TITLE
[Bug]: Unknown regex group name 'DEFINE'

### ISSUE THREAD

**Issue by ChinoCodeDemon** [ThioJoe/YT-Spammer-Purge#890]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

While testing out the YT Spammer Purge script, i did get an exception.

The variable 'phoneRegex' in the file 'Scripts/filter_variables.py' causes the error message, a fix would require a rewrite of the regex string without 'DEFINE'.

I could rewrite the regex expression, if i would have a test string to check if i get the same result or better.

### Release version

2.16.9

### Steps to reproduce

1. Run YTSpammerPurge.py on (arch) linux with updated python version.
2. Scan a video with "auto-smart mode"

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
Traceback (most recent call last):                ]
  File "/home/luna/Documents/projects/python/YT-Spammer-Purge/YTSpammerPurge.py", line 1675, in <module>
    main()
  File "/home/luna/Documents/projects/python/YT-Spammer-Purge/YTSpammerPurge.py", line 1652, in main
    continueRunning = primaryInstance(miscData)
  File "/home/luna/Documents/projects/python/YT-Spammer-Purge/YTSpammerPurge.py", line 1053, in primaryInstance
    filterSettings = modes.prepare_filter_mode_smart(scanMode, config, miscData)
  File "/home/luna/Documents/projects/python/YT-Spammer-Purge/Scripts/prepare_modes.py", line 342, in prepare_filter_mode_smart
    phoneRegexCompiled = re.compile(filter.phoneRegex)
  File "/usr/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 775, in _parse
    raise source.error(msg, len(condname) + 1)
re.error: unknown group name 'DEFINE' at position 3
------------------------------------------------
Error Message: unknown group name 'DEFINE' at position 3
```

**Comment by ChinoCodeDemon** [comment]
It seems that the regex lib didn't load properly, which made it behave weird.
I close this for now, i will reopen if it happens again.

**Comment by paulmikulskis** [comment]
I was having the same issue, looking into how things load now r.e. this thread, thanks for opening the issue in the first place
```
re.error: unknown group name 'DEFINE' at position 3
```

**Comment by paulmikulskis** [comment]
Here is a tip from the regex library on some of the special characters:
```
    (?(DEFINE)...)      If there's no group called "DEFINE", then ... will be
                        ignored, but any group definitions will be available.
```

**Comment by ChinoCodeDemon** [comment]
I think it will be at some point important to fix the issue, since others will also get that problem.
I will probably make a fork and disable this regex entry, until this line is corrected or even research how to get a better result.
