### ISSUE TITLE
Selecting any channel while trying to scan recent community posts crashes

### ISSUE THREAD

**Issue by gallium-gonzollium** [ThioJoe/YT-Spammer-Purge#913]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I selected (5) on the main menu. No matter what channel I choose, even my own by pressing only enter, crashes the program.

### Release version

2.16.9

### Steps to reproduce

1. Go to main menu
2. Press 5 and enter
3. Enter any channel ID
4. Press enter
5. Crash

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
> At any prompt, enter 'X' to return here
> Enter 'Q' now to quit


-------------------------------- Scanning Options --------------------------------
      1. Scan specific videos
      2. Scan recent videos for a channel
      3. Scan recent comments across your Entire Channel
      4. Scan a specific community post (Experimental)
      5. Scan recent community posts for a channel (Experimental)

--------------------------------- Other Options ----------------------------------
      6. Create your own config file(s) to run the program with pre-set settings
      7. Remove comments using a pre-existing list or log file
      8. Recover deleted comments using log file
      9. Check & Download Updates

Choice (1-9): 5

NOTES: This mode is experimental, and not as polished as other features. Expect some janky-ness.
   > It is also much slower to retrieve comments, because it does not use the API

Enter a channel ID or Link to scan recent community posts from
   > If scanning your own channel, just hit Enter

Enter Here:
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1674, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1651, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 846, in primaryInstance
  File "Scripts\community_downloader.py", line 79, in fetch_recent_community_posts
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
------------------------------------------------
Error Message: Expecting value: line 1 column 1 (char 0)

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

 Press Enter to Exit...
```

### Screenshots

![image](https://user-images.githubusercontent.com/97408555/186280102-858248a8-dc16-4812-be9a-e1345e6a5940.png)

**Comment by Firecul** [comment]
Huh, I never spotted that, I've used that feature before too it must have been something recent that broke it.

![image](https://user-images.githubusercontent.com/34950371/187001092-18d6e5b3-4f65-4b3e-8c63-01e5e08eddc3.png)

**Comment by ThioJoe** [comment]
I tried it myself and it didn't produce the error, perhaps it was a temporary issue. Can you check if the error still happens for you?

**Comment by Firecul** [comment]
With the 2.16.9 version yes. I'll try again once I update to the new version

**Comment by ThioJoe** [comment]
Hm I wonder what the difference could be...
<img width="708" alt="image" src="https://user-images.githubusercontent.com/12518330/190520901-2379feda-98f1-4752-9962-fb14cb92afb6.png">

**Comment by Firecul** [comment]
2.16.10 also still errors for me.

![image](https://user-images.githubusercontent.com/34950371/190521830-37a9641c-4a13-436e-97aa-34dafda68e45.png)


Can't test using 2.17 beta branch for a different reason 
![image](https://user-images.githubusercontent.com/34950371/190521983-0870a920-8600-4b6a-a748-38dac7a4b0cb.png)

**Comment by ThioJoe** [comment]
> Can't test using 2.17 beta branch for a different reason
There's a new dependency, try re running installing requirements.txt

**Comment by Firecul** [comment]
Just did. Still have the crash
![image](https://user-images.githubusercontent.com/34950371/190522822-77362eff-8e17-4161-98a7-3fda9d2dff5e.png)

**Comment by ThioJoe** [comment]
Does this still happen?

It looks like on the line with
`data = json.loads(regex_search(html, YT_INITIAL_DATA_RE, default=''))`

The regex_search function is basically returning a default blank string because there was no match to the `YT_INITIAL_DATA_RE` regex expression when searching whatever html it got. I don't think I wrote that expression so I'm not sure what it searches for, but I believe it's trying to fetch a certain part of the webpage to be able to convert to JSON.

I assume it has something to do with the OS environment and what it uses to fetch the pages but I'm not sure.

**Comment by Firecul** [comment]
> Does this still happen?

With `2.17-Beta6` yes, it still happens
![WindowsTerminal_Windows_PowerShell (82)](https://user-images.githubusercontent.com/34950371/208554186-d861afc1-1561-438e-92c0-d3dbe25e56d2.png)
