### ISSUE TITLE
[Bug]: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by barateza** [ThioJoe/YT-Spammer-Purge#915]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to report comments but then received the following error after typing REPORT

(see _relevant log output_)

### Release version

2.16.9

### Steps to reproduce

1. Use option 1 (scan specific video)
2. Use any video
3. Use auto-smart mode
4. REPORT spam comments

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Traceback (most recent call last):[0 / 303] (In Groups of 50)
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1674, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1651, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1600, in primaryInstance
  File "Scripts\operations.py", line 1088, in delete_found_comments
  File "Scripts\operations.py", line 1053, in setStatus
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 922, in execute
  File "googleapiclient\http.py", line 221, in _retry_request
  File "googleapiclient\http.py", line 190, in _retry_request
  File "google_auth_httplib2.py", line 218, in request
  File "httplib2\__init__.py", line 1701, in request
  File "httplib2\__init__.py", line 1421, in _request
  File "httplib2\__init__.py", line 1373, in _conn_request
  File "http\client.py", line 1371, in getresponse
  File "http\client.py", line 319, in begin
  File "http\client.py", line 280, in _read_status
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
------------------------------------------------
Error Message: [WinError 10054] An existing connection was forcibly closed by the remote host

Unknown Error - Code: Z-3 occurred.
```

**Comment by barateza** [comment]
Can confirm it was intermittent and the application is working fine, thanks.
