### ISSUE TITLE
Getting Error Code Z-3 everytime I run the program

### ISSUE THREAD

**Issue by LeYoshi05** [ThioJoe/YT-Spammer-Purge#968]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When I run the program and scan recent videos for a channel, the program keeps crashing with Code Z-3 everytime it saved the log file. Here's the full error:

1. Traceback (most recent call last):
  File "D:\Coding\YT-Spammer-Purge\YTSpammerPurge.py", line 1674, in <module>
    main()
  File "D:\Coding\YT-Spammer-Purge\YTSpammerPurge.py", line 1651, in main
    continueRunning = primaryInstance(miscData)
  File "D:\Coding\YT-Spammer-Purge\YTSpammerPurge.py", line 1286, in primaryInstance
    logFileContents, logMode = logging.print_comments(current, config, scanVideoID, loggingEnabled, scanMode, logMode)
  File "D:\Coding\YT-Spammer-Purge\Scripts\logging.py", line 28, in print_comments
    j, commentsContents = print_prepared_comments(current, commentsContents, scanVideoID, list(current.matchedCommentsDict.keys()), j, loggingEnabled, scanMode, logMode, doWritePrint, matchReason="Filter Match")
  File "D:\Coding\YT-Spammer-Purge\Scripts\logging.py", line 319, in print_prepared_comments
    print(str(j+1) + f". {F.LIGHTCYAN_EX}" + author + f"{S.R}:  {F.YELLOW}" + text + f"{S.R}")
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>
------------------------------------------------
Error Message: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>

### Release version

2.16.10

### Steps to reproduce

1. Start Program
2. Scan videos for Channel
3. Wait
4. Save Logfile
5. Error occurs

### What platform are you seeing this problem on?

Windows (.py script)

### Relevant log output

```shell
1. Traceback (most recent call last):
  File "D:\Coding\YT-Spammer-Purge\YTSpammerPurge.py", line 1674, in <module>
    main()
  File "D:\Coding\YT-Spammer-Purge\YTSpammerPurge.py", line 1651, in main
    continueRunning = primaryInstance(miscData)
  File "D:\Coding\YT-Spammer-Purge\YTSpammerPurge.py", line 1286, in primaryInstance
    logFileContents, logMode = logging.print_comments(current, config, scanVideoID, loggingEnabled, scanMode, logMode)
  File "D:\Coding\YT-Spammer-Purge\Scripts\logging.py", line 28, in print_comments
    j, commentsContents = print_prepared_comments(current, commentsContents, scanVideoID, list(current.matchedCommentsDict.keys()), j, loggingEnabled, scanMode, logMode, doWritePrint, matchReason="Filter Match")
  File "D:\Coding\YT-Spammer-Purge\Scripts\logging.py", line 319, in print_prepared_comments
    print(str(j+1) + f". {F.LIGHTCYAN_EX}" + author + f"{S.R}:  {F.YELLOW}" + text + f"{S.R}")
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>
------------------------------------------------
Error Message: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>
```

**Comment by Firecul** [comment]
Is it happening on all channels or just one?
